/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'daviddecoding' at '7/5/16 1:08 PM' with Gradle 2.11
 *
 * @author daviddecoding, @date 7/5/16 1:08 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
