/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'daviddecoding' at '7/5/16 1:08 PM' with Gradle 2.11
 *
 * @author daviddecoding, @date 7/5/16 1:08 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
